#!/bin/bash

if [ ! $# == 2 ]; then
  echo "Usage: $0 weight_in_kilos height_in_centimeters"
  exit
fi

weight="$1"
height="$2"

idealweight=$[ $height - 110 ]

if [ $weight -le $idealweight ] ; then
  echo "You should eat a bit more fat."
else
  echo "You should eat a bit more fruit."
fi
