#!/bin/bash

clear

echo "This script starts now."
echo

echo "Hi, $USER!"
echo

echo "Here is the list of processes."
echo
ps -l
echo

echo "I'm now setting two variable."
COLOUR="black"
VALUE="9"

echo "This is a string: $COLOUR"
echo "This is a number: $VALUE"
echo

echo "Running you to the command prompt now."
